services:
  instapark-chat-server:
    build:
      context: .
    environment:
      NODE_ENV: production
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 8084:8084
    depends_on:
      - cassandra
      - redis

  instapark-chat-cassandra:
    image: cassandra:4.1
    container_name: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: InstaparkChatCluster"
      CASSANDRA_DC: "InstaparkDataCenter1"
      CASSANDRA_RACK: "InstaparkRack1"
      CASSANDRA_ENDPOINT_SNITCH: "SimpleSnitch"
    ports:
      - 9042:9042

  instapark-chat-redis:
    image: redis:7.2
    container_name: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--save", "", "--appendonly", "no"]
